# Site settings
title: gutoyr stuffs
email: 
description: > # this means to ignore newlines until "baseurl:"
  My place to store and share some finds.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gutoyr.github.io" # the base hostname & protocol for your site
twitter_username: gutoyr
github_username:  gutoyr

# Build settings
#markdown: kramdown
markdown: redcarpet
